backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://miuse-test.com
logo_url: https://your-site.com/images/logo.svg

collections:
  #
  # GENERAL PAGES #######################################################
  #
  - label: 'General'
    name: 'general'
    format: 'json'
    delete: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'assets/content/home.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Register Button', name: 'btn_register', widget: 'string' }
          - { label: 'Login Button', name: 'btn_login', widget: 'string' }
      - label: 'Register'
        name: 'register'
        file: 'assets/content/register.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Intro Message', name: 'body', widget: 'markdown' }
          - { label: 'Copied Message', name: 'copy', widget: 'markdown' }
          - { label: 'Saved Message', name: 'save', widget: 'markdown' }
          - { label: 'Copy Button', name: 'btn_copy', widget: 'string' }
          - { label: 'Save Button', name: 'btn_save', widget: 'string' }
          - { label: 'Next Button', name: 'btn_next', widget: 'string' }
          - { label: 'Back Button', name: 'btn_back', widget: 'string' }
      - label: 'Login'
        name: 'login'
        file: 'assets/content/login.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Intro Message', name: 'body', widget: 'markdown' }
          - { label: 'Login Button', name: 'btn_login', widget: 'string' }
          - { label: 'Cancel Button', name: 'btn_cancel', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: 'assets/content/about.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Back Button', name: 'btn_back', widget: 'string' }
      - label: 'Support'
        name: 'support'
        file: 'assets/content/support.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Back Button', name: 'btn_back', widget: 'string' }
  - name: 'Module Content' # all the things in one entry, for documentation and quick testing
    label: 'Modules'
    folder: '_modules'
    label_singular: 'Module' # Used in the UI, ie: "New Post"
    description: >
      'Create a new module here with it's respective pages. Remember that flow to each page is not linear - users will be directed to the next page based on the decision tree'
    create: true
    meta:
      - { label: 'Module Content', name: 'description', widget: 'text' }
    fields:
      - label: 'Module'
        name: 'module'
        collection: 'module'
        displayFields: ['title', 'date']
        searchFields: ['title', 'body']
        valueField: 'title'
      - { label: 'Title', name: 'title', widget: 'string', hint: 'Name of the module'}
      - { label: 'Text', name: 'text', widget: 'text', hint: 'Description of the module - displayed at the beginning' }
      - { label: 'Number', name: 'number', widget: 'number', hint: 'The ID number of this module' }
      - { label: 'Created On', name: 'datetime', widget: 'datetime' }
      - label: 'Page'
        name: 'page'
        widget: 'object'
        description: >
          Create a new page within this module - routing will be carried out seperately via the decision tree        
        collapsed: true
        fields:
          - label: 'Module Page'
            name: 'page'
            collection: 'pages'
            searchFields: ['title', 'body']
            valueField: 'title'
          - { label: 'ID', name: 'number', widget: 'number' }
          - { label: 'Text', name: 'text', widget: 'text' }
          - { label: 'Image', name: 'image', widget: 'image' }
          - label: 'List'
            description: >
              'Create a list of items to display'
            name: 'list'
            widget: 'list'
            fields:
              - { label: 'Markdown', name: 'markdown', widget: 'markdown' }
          - label: 'User Input'
            hint: 'Add a section requiring user input'
            description: >
              'Add a section requiring user input'
            name: 'form'
            widget: 'list'
            types:
              - label: 'Yes/No Question'
                name: 'binary'
                widget: 'object'
                fields:
                  - { label: 'Question Text', name: 'string', widget: 'string' }
                  - { label: 'Yes Text', name: 'text', widget: 'text' }
                  - { label: 'No text', name: 'text', widget: 'text' }
              - label: 'Slider Question'
                name: 'slider'
                widget: 'object'
                fields:
                  - { label: 'Question Text', name: 'string', widget: 'string' }
                  - { label: 'Yes Text', name: 'text', widget: 'text' }
                  - { label: 'High text', name: 'text', widget: 'text' }             
                  - { label: 'Low text', name: 'text', widget: 'text' }
                  - { label: 'Range', name: 'number', widget: 'number' }
                  - { label: 'Created', name: 'datetime', widget: 'datetime' }
              - label: 'Select and Rank'
                name: 'rank'
                widget: 'list'
                hint: 'User must rank the items in order of preference'
                fields:
                  - { label: 'String', name: 'string', widget: 'string' }
                  - label: 'List'
                    name: 'list'
                    widget: 'list'
                    hint: 'Add an item to the list'
                    fields:
                      - label: 'Related Post'
                        name: 'post'
                        widget: 'relationKitchenSinkPost'
                        collection: 'posts'
                        searchFields: ['title', 'body']
                        valueField: 'title'
                      - { label: 'List Item', name: 'string', widget: 'string' }
                      - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
              - label: 'Multiple Choice Question'
                name: 'choice'
                widget: 'list'
                fields:
                  - { label: 'String', name: 'string', widget: 'string' }
                  - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
                  - label: 'List'
                    name: 'list'
                    widget: 'list'
                    fields:
                      - label: 'Related Post'
                        name: 'post'
                        widget: 'relationKitchenSinkPost'
                        collection: 'posts'
                        searchFields: ['title', 'body']
                        valueField: 'title'
                      - { label: 'List Item', name: 'string', widget: 'string' }
                      - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
              - name: 'Likeart Scale'
                widget: 'list'
                fields:
                  - { label: 'Select No', name: 'number', widget: 'number' }
                  - { label: 'Select', name: 'select', widget: 'select', options: ['a', 'b', 'c'] }
                  - label: 'List'
                    name: 'list'
                    widget: 'list'
                    fields:
                      - label: 'Related Post'
                        name: 'post'
                        widget: 'relationKitchenSinkPost'
                        collection: 'posts'
                        searchFields: ['title', 'body']
                        valueField: 'title'
                      - { label: 'List Item', name: 'string', widget: 'string' }
                      - { label: 'Boolean', name: 'boolean', widget: 'boolean' }
              - name: 'Custom Component'
                widget: 'object'
                hint: 'This is custom component specific to this page/acitivity'
                fields:
                  - { label: 'Component ID', name: 'number', widget: 'number' }
                  - { label: 'Component Name', name: 'string', widget: 'string' }
  - name: "navigation"
    label: "Navigation"
    extension: "json"
    format: "json"
    create: true
    folder: src/data/navigation
    slug: "{{slug}}"
    editor:
       preview: false
    fields:
      - {name: title}
      - name: sections
        label: Sections
        widget: list
        fields:
        - {name: title}
        - name: links
          label: Links
          widget: list
          fields:
            - {name: title}
            - {name: url}
  