backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'assets/content/blog'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'page'
    label: 'Page'
    folder: 'assets/content/page'
    create: true
    format: 'json'
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Text', name: 'text', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  #
  # MODULES
  #
  - label: 'Modules'
    name: 'modules'
    format: 'json'
    delete: false
    create: true
    files:
      - label: 'Module'
        name: 'modules'
        file: 'assets/content/modules/modules.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Id', name: 'Id', widget: 'number' }
          - label: 'Page'
            name: 'page'
            widget: 'list'
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Text', name: 'text', widget: 'string' }
              - { label: 'Id', name: 'id', widget: 'number' }
              - label: 'Form Type'
                name: 'form_type'
                widget: 'select'
                default: 'binary'
                options:
                  - { label: 'Binary', value: 'binary' }
                  - { label: 'Slider', value: 'slider' }
                  - { label: 'Rank', value: 'rank' }
                  - { label: 'MCQ', value: 'MCQ' }
                  - { label: 'Likeart', value: 'likeart' }
                  - { label: 'Custom', value: 'custom' }
              - label: 'Options'
                name: 'options'
                widget: 'list'
                fields:
                  - { label: 'Label', name: 'label', widget: 'string', required: false }
                  - { label: 'Value', name: 'value', widget: 'string' }