backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://miuse-test.com
logo_url: https://ibb.co/59Kndbf
site_url: https://miuse-test.com

# publish_mode: editorial_workflow

collections:
  - name: 'Module Content'
    label: 'Module Content'
    folder: 'assets/content/_pages'
    extension: "json"
    label_singular: 'Page'
    description: >
      Create pages here within each module. Remember that flow to each page is not linear - users will be directed to the next page based on the decision tree.
    create: true
    slug:
      encoding: "ascii"
      clean_accents: true
      sanitize_replacement: "_"
    editor:
      preview: false
    meta:
      - { label: 'Module Content', name: 'description', widget: 'text' }     
    collapsed: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', hint: 'title of this page' }
      - { label: 'ID', name: 'id', widget: 'string', hint: 'ID reference for this page' }
      - { label: 'Introduction', name: 'introduction', widget: 'markdown', hint: 'Introductory text' }
      - label: 'User Input'
        hint: 'Add a section requiring user input'
        description: >
          'Add a section requiring user input'
        name: 'form'
        widget: 'list'
        types:
          
          # 'Yes/No Question'
          - label: 'Yes/No Question'
            name: 'binary'
            widget: 'object'
            hint: Create a yes/no format question
            description: >
              Create a yes/no format question
            fields:
              - { label: 'Question Text', name: 'question_text', widget: 'string' }
              - { label: 'Yes Text', name: 'yes_text', widget: 'string' }
              - { label: 'No Text', name: 'no_text', widget: 'string' }
          
          # 'Slider Question'
          - label: 'Slider Question'
            name: 'slider'
            hint: Create a slider format question
            description: >
              Create a slider question
            widget: 'list'
            fields:
              - { label: 'Question Text', name: 'text', widget: 'string' }
              - { label: 'Label (Low)', name: 'low_label', widget: 'text' }             
              - { label: 'Label (High)', name: 'high_label', widget: 'text' }
              - { label: 'Range', name: 'range', widget: 'number' }
        
          # 'Select and Rank'
          - label: 'Select and Rank'
            name: 'rank'
            widget: 'list'
            create: true
            description: >
              Create a select and rank question
            hint: 'User must rank the items in order of preference'
            fields:
              - { label: 'Question Text', name: 'string', widget: 'string' }
              - { label: 'Complete after', name: 'limit', hint: 'Mark question as completed after count', widget: 'number' }
              - label: 'Select and Rank list item'
                name: 'list'
                widget: 'list'
                hint: 'Add an item to the list'
                slug: "{{year}}-{{month}}-{{day}}_{{fields.slug}}_{{fields.test}}_{{test}"
          
          # 'Multiple Choice Question'
          - label: 'Multiple Choice Question'
            name: 'choice'
            widget: 'list'
            hint: Create a multiple choice question
            description: >
              Create a multiple choice question
            fields:
              - {label: "Test list item", name: "tags", widget: "list"}
              - { label: 'Question Text', name: 'question_text', widget: 'string' }
              - { label: 'Complete after', name: 'limit', hint: 'Mark question as completed after count', widget: 'number' }
              - label: 'Multiple choice list'
                name: 'list'
                widget: 'list'
                hint: 'Add an item to the list'
                fields:
                  - { label: 'List Item', name: 'item', widget: 'string' }
        
          # 'Likeart Scale'
          - label: 'Likeart Scale'
            widget: 'list'
            name: 'likeart'
            hint: Create a Likeart Scale question
            description: >
              Create a Likeart Scale question
            fields:
              - { label: 'Question Text', name: 'string', widget: 'string' }
              - { label: 'Complete after', name: 'number', hint: 'Mark question as completed after count', widget: 'number' }
              - label: 'Items to rank'
                name: 'list item'
                widget: 'list'
                fields:
                  - label: 'Likeart Items'
                  - { label: 'List Item', name: 'items', widget: 'string' }
                  - { label: 'Range', name: 'range', widget: 'number' }
        
          # 'Custom Input'
          - name: 'Custom Input'
            widget: 'object'
            description: >
              Reference a custom component requiring user input
            hint: 'This is custom component specific to this page/activity'
            fields:
              - { label: 'Component ID', name: 'custom_input_id', widget: 'number' }
              - { label: 'Component Name', name: 'name', widget: 'string' }
      
      # 'Custom Component (activities etc)'      
      - { label: 'Custom Component', name: 'is_custom_component', widget: 'boolean', hint: 'This contains a custom component', required: false}
      - { label: 'Custom Component ID', name: 'custom_component_id', widget: 'text', hint: 'The name of the custom object', required: false}
      - { label: 'Final', name: 'final', widget: 'boolean', hint: 'Indicate this is the final page of this module', default: false }

  #
  # GENERAL PAGES #######################################################
  #
  - label: 'General'
    name: 'general'
    format: 'json'
    delete: false
    files:
      - label: 'Home'
        name: 'home'
        file: 'assets/content/home.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Register Button', name: 'btn_register', widget: 'string' }
          - { label: 'Login Button', name: 'btn_login', widget: 'string' }
      - label: 'Register'
        name: 'register'
        file: 'assets/content/register.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Intro Message', name: 'body', widget: 'markdown' }
          - { label: 'Copied Message', name: 'copy', widget: 'markdown' }
          - { label: 'Saved Message', name: 'save', widget: 'markdown' }
          - { label: 'Copy Button', name: 'btn_copy', widget: 'string' }
          - { label: 'Save Button', name: 'btn_save', widget: 'string' }
          - { label: 'Next Button', name: 'btn_next', widget: 'string' }
          - { label: 'Back Button', name: 'btn_back', widget: 'string' }
      - label: 'Login'
        name: 'login'
        file: 'assets/content/login.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Intro Message', name: 'body', widget: 'markdown' }
          - { label: 'Login Button', name: 'btn_login', widget: 'string' }
          - { label: 'Cancel Button', name: 'btn_cancel', widget: 'string' }
      - label: 'Activities'
        name: 'activities'
        file: 'assets/content/activities.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Drug Use', name: 'drugs', widget: 'string' }
          - { label: 'Behavioural Awareness', name: 'awareness', widget: 'string' }
          - { label: 'Relationship Assessment', name: 'relationships', widget: 'string' }
          - { label: 'Goals and Committed Actions', name: 'goals', widget: 'string' }
          - { label: 'Social Norms', name: 'social', widget: 'string' }
          - { label: 'Overall Personalized feedback ', name: 'review', widget: 'string' }
      - label: 'About'
        name: 'about'
        file: 'assets/content/about.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Back Button', name: 'btn_back', widget: 'string' }
      - label: 'Support'
        name: 'support'
        file: 'assets/content/support.json'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
          - { label: 'Back Button', name: 'btn_back', widget: 'string' }
  #
  # Code
  #
  - name: "code"
    label: "Code"
    extension: "json"
    editor:
      preview: true
    files:
      - file: "src/data/code.json"
        label: "Settings"
        name: "settings"
        fields:
          - { name: body, label: Body, widget: code }